"""
utils/report_generator.py — PDF Medical Report Generation
Generates a professional medical report with prediction, confidence, and Grad-CAM.
"""

import os
import sys
from datetime import datetime
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from PIL import Image
import io
import tempfile

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import CLASS_INFO, HOSPITAL_NAME, REPORT_AUTHOR, REPORTS_DIR

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm, mm
    from reportlab.lib.colors import HexColor, white, black
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Image as RLImage,
        Table, TableStyle, HRFlowable
    )
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    print("[Warning] reportlab not installed. PDF generation will be skipped.")


def generate_report(
    patient_name: str,
    patient_age: str,
    patient_id: str,
    original_pil: Image.Image,
    gradcam_fig: plt.Figure,
    predicted_class: str,
    confidence: float,
    all_probabilities: dict,
    save_dir: str = REPORTS_DIR
) -> str:
    """
    Generate a PDF medical report.

    Returns:
        Path to the saved PDF file.
    """
    if not REPORTLAB_AVAILABLE:
        return None

    os.makedirs(save_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"eye_report_{patient_id}_{timestamp}.pdf"
    filepath = os.path.join(save_dir, filename)

    class_data = CLASS_INFO.get(predicted_class.lower().replace(" ", "_"), CLASS_INFO["normal"])
    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm
    )

    story = []
    styles = getSampleStyleSheet()

    # ─── Color Palette ────────────────────────────────────────────────────────
    PRIMARY     = HexColor("#1e3a5f")
    ACCENT      = HexColor("#3b82f6")
    LIGHT_BG    = HexColor("#f0f7ff")
    SEVERITY_COLOR = HexColor(class_data["color"])
    DARK        = HexColor("#1f2937")
    GRAY        = HexColor("#6b7280")

    # ─── Custom Styles ────────────────────────────────────────────────────────
    title_style = ParagraphStyle(
        "Title", parent=styles["Title"],
        fontSize=22, textColor=white, backColor=PRIMARY,
        spaceAfter=0, spaceBefore=0, alignment=TA_CENTER,
        fontName="Helvetica-Bold", leading=30
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontSize=11, textColor=HexColor("#93c5fd"),
        alignment=TA_CENTER, fontName="Helvetica"
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Normal"],
        fontSize=13, textColor=PRIMARY,
        fontName="Helvetica-Bold", spaceBefore=12, spaceAfter=4
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontSize=10, textColor=DARK,
        fontName="Helvetica", leading=16
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"],
        fontSize=8, textColor=GRAY,
        fontName="Helvetica-Oblique", alignment=TA_CENTER, leading=12
    )

    # ─── Header ───────────────────────────────────────────────────────────────
    story.append(Paragraph(f" {HOSPITAL_NAME} ", title_style))
    story.append(Paragraph("AI-Powered Eye Disease Screening Report", subtitle_style))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=2, color=ACCENT))
    story.append(Spacer(1, 8))

    # ─── Report Meta ──────────────────────────────────────────────────────────
    now = datetime.now()
    meta_data = [
        ["Report ID:", f"RPT-{timestamp}", "Date:", now.strftime("%d %B %Y")],
        ["Patient Name:", patient_name or "N/A", "Time:", now.strftime("%H:%M:%S")],
        ["Patient ID:", patient_id or "N/A", "Age:", patient_age or "N/A"],
        ["Generated By:", REPORT_AUTHOR, "", ""],
    ]
    meta_table = Table(meta_data, colWidths=[3.5*cm, 6.5*cm, 2.5*cm, 5*cm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 0), (-1, -1), 9),
        ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",    (2, 0), (2, -1), "Helvetica-Bold"),
        ("TEXTCOLOR",   (0, 0), (0, -1), PRIMARY),
        ("TEXTCOLOR",   (2, 0), (2, -1), PRIMARY),
        ("TEXTCOLOR",   (1, 0), (1, -1), DARK),
        ("TEXTCOLOR",   (3, 0), (3, -1), DARK),
        ("BACKGROUND",  (0, 0), (-1, -1), LIGHT_BG),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LIGHT_BG, white]),
        ("GRID",        (0, 0), (-1, -1), 0.3, HexColor("#d1d5db")),
        ("TOPPADDING",  (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 14))

    # ─── Diagnosis Result ─────────────────────────────────────────────────────
    story.append(Paragraph("▸ DIAGNOSIS RESULT", section_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#d1d5db")))
    story.append(Spacer(1, 6))

    result_data = [
        ["Detected Condition", class_data["display_name"]],
        ["Confidence Score", f"{confidence:.2f}%"],
        ["Severity Level", class_data["severity"]],
        ["Description", class_data["description"]],
        ["Recommendation", class_data["recommendation"]],
    ]
    result_table = Table(result_data, colWidths=[5*cm, 12.5*cm])
    result_table.setStyle(TableStyle([
        ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",    (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 0), (-1, -1), 10),
        ("TEXTCOLOR",   (0, 0), (0, -1), PRIMARY),
        ("TEXTCOLOR",   (1, 0), (1, 0), SEVERITY_COLOR),
        ("FONTNAME",    (1, 0), (1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (1, 0), (1, 0), 13),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [HexColor("#eff6ff"), white]),
        ("GRID",        (0, 0), (-1, -1), 0.3, HexColor("#d1d5db")),
        ("TOPPADDING",  (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN",      (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(result_table)
    story.append(Spacer(1, 14))

    # ─── Confidence Breakdown ─────────────────────────────────────────────────
    story.append(Paragraph("▸ CONFIDENCE BREAKDOWN (All Classes)", section_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#d1d5db")))
    story.append(Spacer(1, 6))

    prob_header = [["Disease Class", "Confidence (%)", "Status"]]
    prob_rows = []
    for cls, prob in sorted(all_probabilities.items(), key=lambda x: x[1], reverse=True):
        display = CLASS_INFO.get(cls, {}).get("display_name", cls)
        status = "✓ DETECTED" if cls == predicted_class else "—"
        prob_rows.append([display, f"{prob:.2f}%", status])

    prob_table = Table(prob_header + prob_rows, colWidths=[8*cm, 5*cm, 4.5*cm])
    prob_table.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR",   (0, 0), (-1, 0), white),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME",    (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [LIGHT_BG, white]),
        ("GRID",        (0, 0), (-1, -1), 0.3, HexColor("#d1d5db")),
        ("ALIGN",       (1, 0), (2, -1), "CENTER"),
        ("TOPPADDING",  (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(prob_table)
    story.append(Spacer(1, 14))

    # ─── Grad-CAM Image ───────────────────────────────────────────────────────
    story.append(Paragraph("▸ EXPLAINABLE AI — GRAD-CAM ANALYSIS", section_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#d1d5db")))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "The Gradient-weighted Class Activation Map (Grad-CAM) highlights the regions "
        "of the retinal image that most influenced the AI model's prediction. "
        "Warmer colors (red/yellow) indicate higher diagnostic significance.",
        body_style
    ))
    story.append(Spacer(1, 6))

    # Save Grad-CAM figure to temp file
    if gradcam_fig is not None:
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            gradcam_path = tmp.name
        gradcam_fig.savefig(gradcam_path, dpi=120, bbox_inches="tight",
                            facecolor=gradcam_fig.get_facecolor())
        plt.close(gradcam_fig)
        story.append(RLImage(gradcam_path, width=17*cm, height=5.5*cm))
        story.append(Spacer(1, 6))

    # ─── Footer / Disclaimer ──────────────────────────────────────────────────
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "⚠️  DISCLAIMER: This report is generated by an AI-based screening system and is "
        "intended for educational and preliminary screening purposes ONLY. It does NOT replace "
        "a clinical diagnosis by a qualified ophthalmologist. Please consult a certified "
        "medical professional before making any healthcare decisions.",
        disclaimer_style
    ))

    # ─── Build PDF ────────────────────────────────────────────────────────────
    doc.build(story)

    # Cleanup temp file
    if gradcam_fig is not None and os.path.exists(gradcam_path):
        os.unlink(gradcam_path)

    return filepath


if __name__ == "__main__":
    print("Report generator module loaded ✓")
